collections:
    projects:
        output: true
    papers:
        output: true
    tutorials:
        output: true

defaults:
    - scope:
        path: ""
        type: "projects"
      values:
        layout: "project"
    - scope:
        path: ""
        type: "papers"
      values:
        layout: "paper"
    - scope:
        path: ""
        type: "tutorials"
      values:
        layout: "tutorial"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"
